---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: guestbook-policy-scc
  namespace: demo-guestbook
  annotations:
    policy.open-cluster-management.io/categories: PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.PT-3 Least Functionality
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  remediationAction: enforce
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["demo-guestbook"]
  object-templates:
    - complianceType: musthave
      objectDefinition:
        allowHostDirVolumePlugin: false
        allowHostIPC: false
        allowHostNetwork: false
        allowHostPID: false
        allowHostPorts: false
        allowPrivilegeEscalation: true
        allowPrivilegedContainer: false
        allowedCapabilities: null
        apiVersion: security.openshift.io/v1
        defaultAddCapabilities: null
        fsGroup:
          type: RunAsAny
        groups:
        - system:cluster-admins
        kind: SecurityContextConstraints
        metadata:
          annotations:
            kubernetes.io/description: anyuid provides all features of the restricted SCC
              but allows users to run with any UID and any GID.
          name: guestbook-scc
          labels:
            app: guestbook-app
        priority: 10
        readOnlyRootFilesystem: false
        requiredDropCapabilities:
        - MKNOD
        runAsUser:
          type: RunAsAny
        seLinuxContext:
          type: MustRunAs
        supplementalGroups:
          type: RunAsAny
        users:
          - 'system:serviceaccount:demo-guestbook:runasanyuid'
        volumes:
        - configMap
        - downwardAPI
        - emptyDir
        - persistentVolumeClaim
        - projected
        - secret
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-guestbook-policy-scc
  namespace: demo-guestbook
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: guestbook-policy-scc
  kind: Policy
  apiGroup: policy.open-cluster-management.io