apiVersion: multicloud.ibm.com/v1beta1
kind: Endpoint
metadata:
  creationTimestamp: null
  name: endpoint
  namespace: multicluster-endpoint
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: false
  clusterLabels:
    cloud: GCP
    vendor: OCP
  clusterName: <CLUSTER_NAME>
  clusterNamespace: <CLUSTER_NAME>
  connectionManager: {}
  iamPolicyController:
    enabled: true
  imagePullSecret: multiclusterhub-operator-pull-secret
  imageRegistry: quay.io/stolostron
  policyController:
    enabled: true
  prometheusIntegration:
    enabled: true
  searchCollector:
    enabled: true
  serviceRegistry:
    dnsSuffix: mcm.svc
    enabled: true
    plugins: kube-service
  topologyCollector:
    enabled: true
    updateInterval: 15
  weaveCollector:
    enabled: false
  version: 1.0.0