---
apiVersion: v1
kind: Namespace
metadata:
  name: <CLUSTER_NAME>
---
apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    cloud: KIND
    name: <CLUSTER_NAME>
    vendor: auto-detect
  name: <CLUSTER_NAME>
  namespace: <CLUSTER_NAME>
spec:
  authInfo: {}
  kubernetesApiEndpoints: {}
---
apiVersion: multicloud.ibm.com/v1alpha1
kind: EndpointConfig
metadata:
  name: <CLUSTER_NAME>
  namespace: <CLUSTER_NAME>
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: false
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  clusterName: <CLUSTER_NAME>
  clusterNamespace: <CLUSTER_NAME>
  iamPolicyController:
    enabled: true
  imageRegistry: quay.io/stolostron
  policyController:
    enabled: true
  prometheusIntegration:
    enabled: true
  searchCollector:
    enabled: true
  serviceRegistry:
    dnsSuffix: mcm.svc
    enabled: true
    plugins: kube-service
  topologyCollector:
    enabled: true
    updateInterval: 15
  weaveCollector:
    enabled: false
  version: 1.0.0
---

