# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: multicluster-hub-custom-registry
    newName: quay.io/stolostron/multicluster-hub-custom-registry
    newTag: 1.0.0-SNAPSHOT-2020-05-12-23-58-57

# list of Resource Config to be Applied
resources:
  - operator-group.yaml
  - subscription.yaml
