
# Copyright Contributors to the Open Cluster Management project

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: default
spec:
  targetNamespaces:
    - "multicluster-engine"