apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-iampolicy
  namespace: default
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.AC Identity Management Authentication and Access Control
    policy.mcm.ibm.com/controls: PR.AC-4 Access Control
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: iam.policies.ibm.com/v1alpha1
        kind: IamPolicy # limit clusteradminrole and report violation in IAM RBAC
        metadata:
          name: policy-iampolicy-example
        spec:
          severity: medium
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform
          maxClusterRoleBindingUsers: 10
          maxRoleBindingViolationsPerNamespace: 2
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-iampolicy
  namespace: default
placementRef:
  name: placement-policy-iampolicy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-iampolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-iampolicy
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions: []